version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./data/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    network_mode: host
    restart: unless-stopped
  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    volumes:
      # Create an .env file that sets the USERDIR environment variable.
      - ./data/matter-server:/data
      - /run/dbus:/run/dbus:ro
    # Required for mDNS to work correctly
    security_opt:
      # Needed for Bluetooth via dbus
      - apparmor:unconfined
    network_mode: host
    restart: unless-stopped
